// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH89SmA9RnEzXN7TiwCpe2UNXccmOuZfg',
    appId: '1:1076653947330:web:f7b2b54310813f70d6be5b',
    messagingSenderId: '1076653947330',
    projectId: 'atta-web-app-a5135',
    authDomain: 'atta-web-app-a5135.firebaseapp.com',
    databaseURL: 'https://atta-web-app-a5135-default-rtdb.firebaseio.com',
    storageBucket: 'atta-web-app-a5135.appspot.com',
    measurementId: 'G-QV3CT7TBMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8H7Fo7uxatEmyPhCrReaPOm5md9JnVbY',
    appId: '1:1076653947330:android:79fa2418b2e17ab2d6be5b',
    messagingSenderId: '1076653947330',
    projectId: 'atta-web-app-a5135',
    databaseURL: 'https://atta-web-app-a5135-default-rtdb.firebaseio.com',
    storageBucket: 'atta-web-app-a5135.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUR_g_iaSt_45zK4na80-cefLmnwnReOI',
    appId: '1:1076653947330:ios:cf9666442afa7c24d6be5b',
    messagingSenderId: '1076653947330',
    projectId: 'atta-web-app-a5135',
    databaseURL: 'https://atta-web-app-a5135-default-rtdb.firebaseio.com',
    storageBucket: 'atta-web-app-a5135.appspot.com',
    iosClientId: '1076653947330-e04c196mnsalcqev97oif31kp50tvn6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProgress',
  );
}
